[features]
seeds = false
skip-lint = false
[programs.localnet]
fctr_staking = "8SxMuTujbukR6KbqJXUuVAdTg6kBWtpmCTb6xpYWqwrP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
